# Generated by Django 5.2.17 on 2026-09-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_managers_payment_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ['-payment_date', '-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
