# Generated by Django 5.2.17 on 2026-09-14 16:32

import django.db.models.deletion
import django.utils.timezone
import insurance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('insurance', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(db_index=True, max_length=100)),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate)),
                ('policy_start_date', models.DateField()),
                ('policy_expiry_date', models.DateField(db_index=True)),
                ('total_premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_records', to='customers.customer')),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_records', to='insurance.insurancecompany')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_records', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Insurance Record',
                'verbose_name_plural': 'Insurance Records',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=insurance.models.insurance_document_upload_path)),
                ('document_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='insurance.insurancerecord')),
            ],
            options={
                'verbose_name': 'Insurance Document',
                'verbose_name_plural': 'Insurance Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
