# Generated by Django 5.2.17 on 2026-09-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_insurancerecord_insurancedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancerecord',
            name='policy_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
