# Generated by Django 5.2.17 on 2026-09-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_insurancerecord_is_active_and_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerecord',
            name='alternative_mobile_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='Alternative Mobile Number'),
        ),
    ]
