# Generated by Django 5.2.17 on 2026-09-28 08:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_insurancerecord_alternative_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerecord',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount given in Rs (applicable only for full payment)', max_digits=12),
        ),
    ]
