# Generated by Django 5.2.17 on 2026-09-30 20:16

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_managers_customer_deleted_at_and_more'),
        ('insurance', '0007_insurancerecord_previous_policy'),
        ('vehicles', '0002_alter_vehicle_managers_vehicle_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='insurancecompany',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='insurancedocument',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='insurancerecord',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='insurancerecord',
            name='unique_active_insurance_per_vehicle',
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='deletion_batch',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='deletion_batch',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='insurancerecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='insurancerecord',
            name='deletion_batch',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='insurancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('vehicle',), name='unique_active_insurance_per_vehicle'),
        ),
    ]
