# Generated by Django 5.2.17 on 2026-09-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_alter_insurancecompany_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurancecompany',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ['name'], 'verbose_name': 'Insurance Company', 'verbose_name_plural': 'Insurance Companies'},
        ),
        migrations.AlterModelOptions(
            name='insurancedocument',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ['-uploaded_at'], 'verbose_name': 'Insurance Document', 'verbose_name_plural': 'Insurance Documents'},
        ),
        migrations.AlterModelOptions(
            name='insurancerecord',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ['-entry_date', '-created_at'], 'verbose_name': 'Insurance Record', 'verbose_name_plural': 'Insurance Records'},
        ),
    ]
