# Generated by Django 5.2.17 on 2026-09-30 21:00

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor_id', models.CharField(blank=True, editable=False, max_length=255)),
                ('actor_username', models.CharField(blank=True, editable=False, max_length=255)),
                ('source', models.CharField(default='system', editable=False, max_length=10)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted (archived)'), ('restore', 'Restored'), ('login', 'Logged in'), ('logout', 'Logged out'), ('password_change', 'Password changed')], editable=False, max_length=20)),
                ('object_type', models.CharField(editable=False, max_length=100)),
                ('object_id', models.CharField(editable=False, max_length=255)),
                ('changes', models.JSONField(default=dict, editable=False)),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('request_method', models.CharField(blank=True, editable=False, max_length=10)),
                ('request_path', models.CharField(blank=True, editable=False, max_length=512)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'default_permissions': ('view',),
                'base_manager_name': 'objects',
                'indexes': [models.Index(fields=['occurred_at', 'id'], name='audit_time_idx'), models.Index(fields=['actor_id', 'occurred_at'], name='audit_actor_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_object_idx'), models.Index(fields=['action', 'occurred_at'], name='audit_action_idx')],
            },
        ),
    ]
