# Generated by Django 5.2.17 on 2026-09-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'base_manager_name': 'objects', 'default_permissions': ('view',), 'ordering': ['-occurred_at', '-id'], 'verbose_name': 'Staff activity', 'verbose_name_plural': 'Staff activity logs'},
        ),
        migrations.AddField(
            model_name='activitylog',
            name='customer_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='customer_phone',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='device',
            field=models.CharField(blank=True, editable=False, help_text='Reported by the browser; this is not a verified computer name.', max_length=120, verbose_name='Browser / system'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True, verbose_name='IP address'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='object_label',
            field=models.CharField(blank=True, editable=False, max_length=512, verbose_name='Affected record'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='policy_number',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='search_text',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='summary',
            field=models.CharField(blank=True, editable=False, max_length=1000, verbose_name='Activity'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.CharField(blank=True, editable=False, max_length=512),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='vehicle_number',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
