# Generated by Django 5.2.17 on 2026-09-30 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('target', models.CharField(choices=[('customers', 'Customers'), ('insurance', 'Insurance records')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bulk upload template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UploadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bulk_upload.uploadtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='UploadColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(help_text='Header displayed in the downloadable Excel template.', max_length=150)),
                ('field_name', models.CharField(choices=[('name', 'Customer name (name)'), ('phone', 'Mobile number (phone)'), ('alternative_mobile_number', 'Alternative mobile number (alternative_mobile_number)'), ('email', 'Email (email)'), ('address', 'Address (address)'), ('customer_name', 'Customer name (customer_name)'), ('customer_phone', 'Mobile number (customer_phone)'), ('customer_alternative_mobile_number', 'Alternative mobile number (customer_alternative_mobile_number)'), ('customer_email', 'Email (customer_email)'), ('customer_address', 'Address (customer_address)'), ('vehicle_number', 'Vehicle number (vehicle_number)'), ('vehicle_type', 'Vehicle type (vehicle_type)'), ('insurance_company_name', 'Insurance company name (insurance_company_name)'), ('policy_number', 'Policy number (policy_number)'), ('entry_date', 'Entry date (entry_date)'), ('policy_start_date', 'Policy start date (policy_start_date)'), ('policy_expiry_date', 'Policy expiry date (policy_expiry_date)'), ('total_premium', 'Total premium (total_premium)'), ('discount', 'Discount (discount)'), ('remarks', 'Remarks (remarks)')], max_length=60)),
                ('aliases', models.TextField(blank=True, help_text='Alternative Excel headers, one per line.')),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, help_text='Used when the column or cell is empty. Dates: YYYY-MM-DD.', max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='bulk_upload.uploadtemplate')),
            ],
            options={
                'verbose_name': 'Upload column',
                'ordering': ['position', 'id'],
            },
        ),
    ]
