# Generated by Django 5.2.17 on 2026-09-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_upload', '0003_alter_uploadreceipt_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadcolumn',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ['position', 'id'], 'verbose_name': 'Upload column'},
        ),
        migrations.AlterModelOptions(
            name='uploadtemplate',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ['name'], 'verbose_name': 'Bulk upload template'},
        ),
    ]
