# Generated by Django 5.2.17 on 2026-09-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usersessionactivity_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersessionactivity',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'verbose_name': 'User Session Activity', 'verbose_name_plural': 'User Session Activities'},
        ),
    ]
