# Generated by Django 5.2.17 on 2026-09-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='alternative_mobile_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Alternative Mobile Number'),
        ),
    ]
