# Generated by Django 5.2.17 on 2026-09-25 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customer_alternative_mobile_number'),
        ('insurance', '0005_insurancerecord_alternative_mobile_number'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Master toggle to enable or disable WhatsApp sending.')),
                ('test_mode', models.BooleanField(default=True, help_text='When test mode is enabled, messages are redirected to the test phone number instead of customers.')),
                ('test_phone_number', models.CharField(blank=True, default='', help_text='Admin test phone number (with country code, e.g. 919876543210) for testing before live deployment.', max_length=20)),
                ('phone_number_id', models.CharField(blank=True, default='', help_text='Meta WhatsApp Phone Number ID (from Meta Developer App -> WhatsApp -> API Setup).', max_length=100)),
                ('waba_id', models.CharField(blank=True, default='', help_text='WhatsApp Business Account ID (WABA ID).', max_length=100)),
                ('access_token', models.TextField(blank=True, default='', help_text='Meta System User Permanent Access Token (or 24-hr Temporary Token for testing).')),
                ('api_version', models.CharField(default='v21.0', help_text='Meta Graph API version (default: v21.0).', max_length=10)),
                ('default_country_code', models.CharField(default='91', help_text='Default country code without plus sign (e.g. 91 for India).', max_length=5)),
                ('policy_template_name', models.CharField(default='insurance_policy_issued', help_text='Meta-approved Template Name for newly issued insurance policies.', max_length=100)),
                ('policy_template_language', models.CharField(default='en', help_text='Language code of the approved policy template (e.g. en, en_US, hi).', max_length=10)),
                ('payment_template_name', models.CharField(default='payment_receipt_collected', help_text='Meta-approved Template Name for payment receipts.', max_length=100)),
                ('payment_template_language', models.CharField(default='en', help_text='Language code of the approved payment template (e.g. en, en_US, hi).', max_length=10)),
                ('webhook_verify_token', models.CharField(blank=True, default='insure_wa_webhook_secret_key', help_text='Secret token configured in Meta Developer App Webhooks to verify endpoint authenticity.', max_length=100)),
                ('auto_send_policy_creation', models.BooleanField(default=True, help_text='Automatically send WhatsApp message when an insurance record is created or renewed.')),
                ('auto_send_payment_receipt', models.BooleanField(default=True, help_text='Automatically send WhatsApp message when a payment is collected.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Configuration',
                'verbose_name_plural': 'WhatsApp Configuration',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(db_index=True, max_length=25)),
                ('message_type', models.CharField(choices=[('POLICY_ISSUED', 'Policy Issued'), ('PAYMENT_RECEIPT', 'Payment Receipt'), ('TEST', 'Test Message'), ('CUSTOM', 'Custom Message')], default='POLICY_ISSUED', max_length=30)),
                ('template_name', models.CharField(blank=True, default='', max_length=100)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent to Meta'), ('delivered', 'Delivered to Phone'), ('read', 'Read by Customer'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('wamid', models.CharField(blank=True, db_index=True, default='', help_text='Meta WhatsApp Message ID', max_length=150)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('is_test', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='customers.customer')),
                ('insurance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='insurance.insurancerecord')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='payments.payment')),
            ],
            options={
                'verbose_name': 'WhatsApp Message Log',
                'verbose_name_plural': 'WhatsApp Message Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
