# Generated by Django 5.2.17 on 2026-09-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0002_alter_whatsappconfig_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappconfig',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'verbose_name': 'WhatsApp Configuration', 'verbose_name_plural': 'WhatsApp Configuration'},
        ),
        migrations.AlterModelOptions(
            name='whatsappmessagelog',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ['-created_at'], 'verbose_name': 'WhatsApp Message Log', 'verbose_name_plural': 'WhatsApp Message Logs'},
        ),
    ]
