# Generated by Django 5.2.17 on 2026-09-30 22:02

import datetime
import django.db.models.deletion
import whatsapp_integration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_alter_insurancecompany_options_and_more'),
        ('whatsapp_integration', '0003_alter_whatsappconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconfig',
            name='renewal_daily_cap',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='renewal_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='renewal_holidays',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='renewal_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='renewal_last_attempt_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='renewal_send_time',
            field=models.TimeField(default=datetime.time(10, 30)),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='renewal_skip_holidays',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='renewal_skip_sundays',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='renewal_stages',
            field=models.JSONField(blank=True, default=whatsapp_integration.models.default_renewal_stages),
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='delivery_events',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='message_type',
            field=models.CharField(choices=[('POLICY_ISSUED', 'Policy Issued'), ('PAYMENT_RECEIPT', 'Payment Receipt'), ('TEST', 'Test Message'), ('CUSTOM', 'Custom Message'), ('RENEWAL_REMINDER', 'Renewal Reminder')], default='POLICY_ISSUED', max_length=30),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent to Meta'), ('delivered', 'Delivered to Phone'), ('read', 'Read by Customer'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='queued', max_length=20),
        ),
        migrations.CreateModel(
            name='RenewalReminderJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField()),
                ('stage', models.PositiveSmallIntegerField()),
                ('source', models.CharField(default='automatic', max_length=12)),
                ('is_test', models.BooleanField(default=False)),
                ('status', models.CharField(db_index=True, default='queued', max_length=12)),
                ('reason', models.TextField(blank=True)),
                ('recipient_phone', models.CharField(blank=True, max_length=25)),
                ('attempted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp_integration.whatsappmessagelog')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_reminders', to='insurance.insurancerecord')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_test', False)), fields=('record', 'expiry_date', 'stage'), name='unique_policy_renewal_stage')],
            },
        ),
    ]
