# Generated by Django 5.2.17 on 2026-09-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0004_whatsappconfig_renewal_daily_cap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewalReminderOptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=25, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
