# Generated by Django 5.2.17 on 2026-09-30 22:16

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0005_renewalreminderoptout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renewalreminderjob',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='renewalreminderoptout',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='renewalreminderjob',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='renewalreminderoptout',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='renewalreminderjob',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='renewalreminderjob',
            name='deletion_batch',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='renewalreminderoptout',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='renewalreminderoptout',
            name='deletion_batch',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
