# Generated by Django 5.2.17 on 2026-09-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='export_pin',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='pin_otp',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='pin_otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
