# Generated by Django 5.2.17 on 2026-09-30 20:16

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_businesssettings_export_pin_businesssettings_pin_otp_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='businesssettings',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='deletion_batch',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
