# Generated by Django 5.2.17 on 2026-09-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_alter_businesssettings_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesssettings',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'verbose_name': 'Business Settings', 'verbose_name_plural': 'Business Settings'},
        ),
    ]
